### ISSUE TITLE
Problem running on GPU (at deserialization): 'GPT2Config' object has no attribute '_to_dict_new'

### ISSUE THREAD

**Issue by happen2me** [Lightning-AI/lightning#15275]
### Bug description

When I use LightningModel to wrap my script and to make it run on GPU, it gives me the following error message:

While, if I don't set the accelerator to GPU or don't use the lit model, the error won't occur.

### How to reproduce the bug

```python
import torch
from torch.utils.data import DataLoader
from transformers import GPT2Config, GPT2LMHeadModel,  GPT2Tokenizer
import pytorch_lightning as pl
from datasets import load_dataset


class LitModel(pl.LightningModule):
    def __init__(self, model):
        super().__init__()
        self.model = model

    def training_step(self, batch):
        input_ids, labels = batch['input_ids'], batch['input_ids']
        return self.model(input_ids=input_ids, labels=labels)

    def configure_optimizers(self):
        return torch.optim.Adam(self.model.parameters())


if __name__ == '__main__':
    conf = GPT2Config()
    model = GPT2LMHeadModel(conf)
    lit_model = LitModel(model)
    trainer = pl.Trainer(accelerator='gpu', max_epochs=2)
    tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
    tokenizer.add_special_tokens({'pad_token': '[PAD]'})
    model.resize_token_embeddings(len(tokenizer))
    # load a random small dataset
    dataset = load_dataset('trec')['test']
    # tokenzie the dataset
    dataset = dataset.map(lambda example: tokenizer(example['text'],
                                                    padding='max_length',
                                                    max_length=32,
                                                    truncation=True))
    # remove non-tensor columns. The columns to remove can also be
    # ['coarse_label', 'fine_label', 'text']
    dataset = dataset.remove_columns(['label-coarse', 'label-fine', 'text'])
    dataset.set_format('torch')
    dataloader = DataLoader(dataset, batch_size=2)
    trainer.fit(lit_model, dataloader)
```

### Error messages and logs

```

Exception has occurred: AttributeError       (note: full exception trace is shown but execution is paused at: <module>)
'GPT2Config' object has no attribute '_to_dict_new'
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/transformers/configuration_utils.py", line 252, in __getattribute__
    return super().__getattribute__(key)
  File ".../miniconda3/envs/pet/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File ".../miniconda3/envs/pet/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "<string>", line 1, in <module> (Current frame)

```

### Environment

* CUDA:
        - GPU:
                - NVIDIA RTX A5000
                - NVIDIA RTX A5000
        - available:         True
        - version:           11.3
* Lightning:
        - pytorch-lightning: 1.7.4
        - torch:             1.12.1+cu113
        - torch-tb-profiler: 0.4.0
        - torchaudio:        0.12.1+cu113
        - torchmetrics:      0.9.3
        - torchvision:       0.13.1+cu113
* Packages:
        - absl-py:           1.2.0
        - adapter-transformers: 3.0.1
        - aiohttp:           3.8.1
        - aiosignal:         1.2.0
        - anyio:             3.6.1
        - argon2-cffi:       21.3.0
        - argon2-cffi-bindings: 21.2.0
        - astroid:           2.11.7
        - asttokens:         2.0.8
        - async-timeout:     4.0.2
        - attrs:             22.1.0
        - autopep8:          1.7.0
        - babel:             2.10.3
        - backcall:          0.2.0
        - beautifulsoup4:    4.11.1
        - bleach:            5.0.1
        - cachetools:        5.2.0
        - certifi:           2022.6.15
        - cffi:              1.15.1
        - charset-normalizer: 2.1.1
        - click:             8.1.3
        - cycler:            0.11.0
        - datasets:          2.4.0
        - debugpy:           1.6.3
        - decorator:         5.1.1
        - defusedxml:        0.7.1
        - dill:              0.3.5.1
        - einops:            0.5.0
        - einops-exts:       0.0.3
        - entrypoints:       0.4
        - evaluate:          0.2.2
        - executing:         0.10.0
        - fastjsonschema:    2.16.1
        - filelock:          3.8.0
        - flake8:            5.0.4
        - fonttools:         4.37.1
        - frozenlist:        1.3.1
        - fsspec:            2022.7.1
        - google-auth:       2.11.0
        - google-auth-oauthlib: 0.4.6
        - grpcio:            1.48.1
        - huggingface-hub:   0.9.0
        - idna:              3.3
        - importlib-metadata: 4.12.0
        - ipykernel:         6.15.1
        - ipython:           8.4.0
        - ipython-genutils:  0.2.0
        - ipywidgets:        8.0.2
        - isodate:           0.6.1
        - isort:             5.10.1
        - jedi:              0.18.1
        - jinja2:            3.1.2
        - joblib:            1.1.0
        - json5:             0.9.10
        - jsonschema:        4.14.0
        - jupyter-client:    7.3.4
        - jupyter-core:      4.11.1
        - jupyter-server:    1.18.1
        - jupyterlab:        3.4.5
        - jupyterlab-pygments: 0.2.2
        - jupyterlab-server: 2.15.0
        - jupyterlab-widgets: 3.0.3
        - kiwisolver:        1.4.4
        - lazy-object-proxy: 1.7.1
        - lxml:              4.9.1
        - markdown:          3.4.1
        - markupsafe:        2.1.1
        - matplotlib:        3.5.3
        - matplotlib-inline: 0.1.6
        - mccabe:            0.7.0
        - mistune:           2.0.4
        - multidict:         6.0.2
        - multiprocess:      0.70.13
        - nbclassic:         0.4.3
        - nbclient:          0.6.7
        - nbconvert:         7.0.0
        - nbformat:          5.4.0
        - nbstripout:        0.6.0
        - nest-asyncio:      1.5.5
        - nltk:              3.7
        - nodejs:            0.1.1
        - notebook:          6.4.12
        - notebook-shim:     0.1.0
        - numpy:             1.23.2
        - oauthlib:          3.2.0
        - optional-django:   0.1.0
        - packaging:         21.3
        - pandas:            1.4.3
        - pandocfilters:     1.5.0
        - parso:             0.8.3
        - pexpect:           4.8.0
        - pickleshare:       0.7.5
        - pillow:            9.2.0
        - pip:               22.1.2
        - platformdirs:      2.5.2
        - prometheus-client: 0.14.1
        - prompt-toolkit:    3.0.30
        - protobuf:          3.19.4
        - psutil:            5.9.1
        - ptyprocess:        0.7.0
        - pure-eval:         0.2.2
        - pyarrow:           9.0.0
        - pyasn1:            0.4.8
        - pyasn1-modules:    0.2.8
        - pycodestyle:       2.9.1
        - pycparser:         2.21
        - pydeprecate:       0.3.2
        - pydocstyle:        6.1.1
        - pyflakes:          2.5.0
        - pygments:          2.13.0
        - pylama:            8.4.1
        - pylint:            2.14.5
        - pyparsing:         3.0.9
        - pyrsistent:        0.18.1
        - python-dateutil:   2.8.2
        - pytorch-lightning: 1.7.4
        - pytz:              2022.2.1
        - pyyaml:            6.0
        - pyzmq:             23.2.1
        - rdflib:            6.1.1
        - regex:             2022.8.17
        - requests:          2.28.1
        - requests-oauthlib: 1.3.1
        - responses:         0.18.0
        - rouge-score:       0.1.2
        - rsa:               4.9
        - sacremoses:        0.0.53
        - scikit-learn:      1.1.2
        - scipy:             1.9.0
        - seaborn:           0.12.1
        - send2trash:        1.8.0
        - setuptools:        63.4.1
        - six:               1.16.0
        - sklearn:           0.0
        - sniffio:           1.2.0
        - snowballstemmer:   2.2.0
        - soupsieve:         2.3.2.post1
        - sparqlwrapper:     1.8.4
        - stack-data:        0.4.0
        - tensorboard:       2.10.0
        - tensorboard-data-server: 0.6.1
        - tensorboard-plugin-wit: 1.8.1
        - terminado:         0.15.0
        - threadpoolctl:     3.1.0
        - tinycss2:          1.1.1
        - tokenizers:        0.12.1
        - toml:              0.10.2
        - tomli:             2.0.1
        - tomlkit:           0.11.4
        - torch:             1.12.1+cu113
        - torch-tb-profiler: 0.4.0
        - torchaudio:        0.12.1+cu113
        - torchmetrics:      0.9.3
        - torchvision:       0.13.1+cu113
        - tornado:           6.2
        - tqdm:              4.64.0
        - traitlets:         5.3.0
        - transformers:      4.21.1
        - typing-extensions: 4.3.0
        - urllib3:           1.26.12
        - wcwidth:           0.2.5
        - webencodings:      0.5.1
        - websocket-client:  1.3.3
        - werkzeug:          2.2.2
        - wheel:             0.37.1
        - widgetsnbextension: 4.0.2
        - wrapt:             1.14.1
        - xxhash:            3.0.0
        - yarl:              1.8.1
        - zipp:              3.8.1
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.9.12
        - version:           #58-Ubuntu SMP Fri Aug 26 05:50:00 UTC 2022

**Comment by tshu-w** [comment]
The above code works fine in my environment.
```
transformers             4.23.1
datasets                 2.6.1
pytorch-lightning        1.7.7
torch                    1.12.1+cu113
```

**Comment by rohitgr7** [comment]
for some reason, this is giving me no dataset
```
dataset = dataset.remove_columns(['label-coarse', 'label-fine', 'text'])
```
is deleting whole dataset for me. can you check?

**Comment by happen2me** [comment]
> for some reason, this is giving me no dataset
> 
> ```
> dataset = dataset.remove_columns(['label-coarse', 'label-fine', 'text'])
> ```
> 
> is deleting whole dataset for me. can you check?

Sorry, it indeed removes all columns. I forgot to assign the tokenized dataset to a variable. Now I corrected the code. Thanks :)

**Comment by happen2me** [comment]
> for some reason, this is giving me no dataset
> 
> ```
> dataset = dataset.remove_columns(['label-coarse', 'label-fine', 'text'])
> ```
> 
> is deleting whole dataset for me. can you check?

Thanks for checking my code. Maybe it has something to do with my environment then :(

**Comment by happen2me** [comment]
> The above code works fine in my environment.
> 
> ```
> transformers             4.23.1
> datasets                 2.6.1
> pytorch-lightning        1.7.7
> torch                    1.12.1+cu113
> ```

Thanks for checking my code. Maybe it has something to do with my environment then :(

**Comment by rohitgr7** [comment]
still not working on single device either. Can you check your example again ? :)

**Comment by rohitgr7** [comment]
still not working..
this is what I ran:
```py
import torch
from torch.utils.data import DataLoader
from transformers import GPT2Config, GPT2LMHeadModel,  GPT2Tokenizer
import pytorch_lightning as pl
from datasets import load_dataset


class LitModel(pl.LightningModule):
    def __init__(self, model):
        super().__init__()
        self.model = model

    def training_step(self, batch):
        input_ids, labels = batch['input_ids'], batch['input_ids']
        breakpoint()
        return self.model(input_ids=input_ids, labels=labels)

    def configure_optimizers(self):
        return torch.optim.Adam(self.model.parameters())


if __name__ == '__main__':
    conf = GPT2Config()
    model = GPT2LMHeadModel(conf)
    lit_model = LitModel(model)
    trainer = pl.Trainer(accelerator='gpu', max_epochs=2, devices=1)
    tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
    tokenizer.add_special_tokens({'pad_token': '[PAD]'})
    # load a random small dataset
    dataset = load_dataset('trec')['test']
    # tokenzie the dataset
    dataset = dataset.map(lambda example: tokenizer(example['text'],
                                                    padding='max_length',
                                                    max_length=32,
                                                    truncation=True))
    # remove non-tensor columns. The columns to remove can also be
    # ['coarse_label', 'fine_label', 'text']
    dataset = dataset.remove_columns(['label-coarse', 'label-fine', 'text'])
    dataloader = DataLoader(dataset, batch_size=2)
    trainer.fit(lit_model, dataloader)
```
can you run it on your system and fix the code to get the error you raised in the issue?

**Comment by happen2me** [comment]
@rohitgr7 I'm sorry, I left out one line `dataset.set_format('torch')`. Now it should work.

Interestingly, I found that if I set `devices=1`, another error arises:
```
...
../aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [171,0,0], thread: [94,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [171,0,0], thread: [95,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
    results = self._run_stage()
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1252, in _run_stage
    return self._run_train()
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1283, in _run_train
    self.fit_loop.run()
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 271, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 203, in advance
    batch_output = self.batch_loop.run(kwargs)
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 87, in advance
    outputs = self.optimizer_loop.run(optimizers, kwargs)
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 201, in advance
    result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 248, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, kwargs.get("batch_idx", 0), closure)
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 358, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1550, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/pytorch_lightning/core/module.py", line 1674, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/pytorch_lightning/core/optimizer.py", line 168, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 216, in optimizer_step
    return self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 153, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/torch/optim/optimizer.py", line 113, in wrapper
    return func(*args, **kwargs)
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/torch/optim/adam.py", line 118, in step
    loss = closure()
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 138, in _wrap_closure
    closure_result = closure()
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 146, in __call__
    self._result = self.closure(*args, **kwargs)
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 132, in closure
    step_output = self._step_fn()
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 407, in _training_step
    training_step_output = self.trainer._call_strategy_hook("training_step", *kwargs.values())
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1704, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 358, in training_step
    return self.model.training_step(*args, **kwargs)
  File "/home/extra/micheal/pet/debug5.py", line 15, in training_step
    return model(input_ids=input_ids, labels=labels)
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1069, in forward
    transformer_outputs = self.transformer(
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/transformers/adapters/context.py", line 103, in wrapper_func
    results = f(self, *args, **kwargs)
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 905, in forward
    outputs = block(
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 407, in forward
    attn_outputs = self.attn(
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 325, in forward
    query, key, value = self.c_attn(hidden_states).split(self.split_size, dim=2)
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File ".../miniconda3/envs/pet/lib/python3.9/site-packages/transformers/modeling_utils.py", line 1871, in forward
    x = torch.addmm(self.bias, x.view(-1, x.size(-1)), self.weight)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

During handling of the above exception, another exception occurred:

...
```

I'm researching why this happens.
